spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lablink_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xxx

  # Redis 配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 10s
      connect-timeout: 5s

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# MinIO 配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: lablink_admin
  secretKey: lablink_123456
  bucketName: lablink-files

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 验证码配置
lablink:
  captcha:
    enabled: true
